// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgXf_nLOx9JQzhl-eCIuzryw5lhKGGVE',
    appId: '1:134606513806:web:925713a5572d72df40cbdf',
    messagingSenderId: '134606513806',
    projectId: 'todoapp-fd497',
    authDomain: 'todoapp-fd497.firebaseapp.com',
    storageBucket: 'todoapp-fd497.appspot.com',
    measurementId: 'G-PLPF7GCT33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt0xVJWtt0c7-goqqu_mar5m9phKbL2qQ',
    appId: '1:134606513806:android:cb1f827bb590020d40cbdf',
    messagingSenderId: '134606513806',
    projectId: 'todoapp-fd497',
    storageBucket: 'todoapp-fd497.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0Q50yOR9Ry9QePTMZVj-wTxohUm_-bE',
    appId: '1:134606513806:ios:bd8c6a94c9437c7440cbdf',
    messagingSenderId: '134606513806',
    projectId: 'todoapp-fd497',
    storageBucket: 'todoapp-fd497.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr0Q50yOR9Ry9QePTMZVj-wTxohUm_-bE',
    appId: '1:134606513806:ios:bd8c6a94c9437c7440cbdf',
    messagingSenderId: '134606513806',
    projectId: 'todoapp-fd497',
    storageBucket: 'todoapp-fd497.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIgXf_nLOx9JQzhl-eCIuzryw5lhKGGVE',
    appId: '1:134606513806:web:da32b1f9e7badb6840cbdf',
    messagingSenderId: '134606513806',
    projectId: 'todoapp-fd497',
    authDomain: 'todoapp-fd497.firebaseapp.com',
    storageBucket: 'todoapp-fd497.appspot.com',
    measurementId: 'G-KR7216R94N',
  );
}
