// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfzRvdlhP7ykOcBORYJiJBm63bvhTNyyc',
    appId: '1:390757415412:web:41cd9741e34427aab7e1a1',
    messagingSenderId: '390757415412',
    projectId: 'todo-c4c91',
    authDomain: 'todo-c4c91.firebaseapp.com',
    storageBucket: 'todo-c4c91.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKwfGRvNdisCigaefKmkcXBc8bVchBWQA',
    appId: '1:390757415412:android:4228e18e4ee7df0db7e1a1',
    messagingSenderId: '390757415412',
    projectId: 'todo-c4c91',
    storageBucket: 'todo-c4c91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIXVqhUpR4y8jfezXxErFmY5DgX5IWAYE',
    appId: '1:390757415412:ios:986819123da5474ab7e1a1',
    messagingSenderId: '390757415412',
    projectId: 'todo-c4c91',
    storageBucket: 'todo-c4c91.appspot.com',
    iosBundleId: 'com.example.mohdSamiTk2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIXVqhUpR4y8jfezXxErFmY5DgX5IWAYE',
    appId: '1:390757415412:ios:986819123da5474ab7e1a1',
    messagingSenderId: '390757415412',
    projectId: 'todo-c4c91',
    storageBucket: 'todo-c4c91.appspot.com',
    iosBundleId: 'com.example.mohdSamiTk2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfzRvdlhP7ykOcBORYJiJBm63bvhTNyyc',
    appId: '1:390757415412:web:7434332f31ee11bbb7e1a1',
    messagingSenderId: '390757415412',
    projectId: 'todo-c4c91',
    authDomain: 'todo-c4c91.firebaseapp.com',
    storageBucket: 'todo-c4c91.appspot.com',
  );
}
